{"name": "更新用户用户", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../api/wework.yaml'", "trace": "self = <WechatAPI.testcase.test_work.TestWework object at 0x00000209D569B438>\n\n    @allure.title(\"更新用户用户\")\n    def test_update_work(self):\n>       print(Wework().test_update_member(\"qw123\",\"更改\",\"13445655456\"))\n\nWechatAPI\\testcase\\test_work.py:27: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <WechatAPI.api.we_work.Wework object at 0x00000209D569B6D8>\n\n    def __init__(self):\n        self.token = Util().token() #不要忘了Util的()\n        self.params[\"token\"]=self.token #要记得替换token的变量\n    \n>       with open(\"../api/wework.yaml\",encoding=\"utf-8\")as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../api/wework.yaml'\n\nWechatAPI\\api\\we_work.py:27: FileNotFoundError"}, "start": 1647487510286, "stop": 1647487510622, "uuid": "d1c4f425-2908-4f06-ba2a-d4240a021b22", "historyId": "83b3ceaefcbf92c647135202cd66afdf", "testCaseId": "99feb50a13057b869e1c8a5a2434592d", "fullName": "WechatAPI.testcase.test_work.TestWework#test_update_work", "labels": [{"name": "parentSuite", "value": "WechatAPI.testcase"}, {"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestWework"}, {"name": "host", "value": "ZXJ"}, {"name": "thread", "value": "64376-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "WechatAPI.testcase.test_work"}]}